// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxEzuu_OPJ7aC8Jar-oAcjfar6rJWss_M',
    appId: '1:319261859233:web:f3d53f350499d684cc3fe0',
    messagingSenderId: '319261859233',
    projectId: 'evently-app-7e57a',
    authDomain: 'evently-app-7e57a.firebaseapp.com',
    storageBucket: 'evently-app-7e57a.firebasestorage.app',
    measurementId: 'G-G9MY56ETVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaeYPfjxDekyHfh4MGDoB6xCFoDZkBpBc',
    appId: '1:319261859233:android:b871321c3f055144cc3fe0',
    messagingSenderId: '319261859233',
    projectId: 'evently-app-7e57a',
    storageBucket: 'evently-app-7e57a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4LPml36mFQSqTeiTfKZp5vA8V3M6bIgA',
    appId: '1:319261859233:ios:6597ac117dc5fda8cc3fe0',
    messagingSenderId: '319261859233',
    projectId: 'evently-app-7e57a',
    storageBucket: 'evently-app-7e57a.firebasestorage.app',
    iosBundleId: 'com.example.eventPlaningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4LPml36mFQSqTeiTfKZp5vA8V3M6bIgA',
    appId: '1:319261859233:ios:6597ac117dc5fda8cc3fe0',
    messagingSenderId: '319261859233',
    projectId: 'evently-app-7e57a',
    storageBucket: 'evently-app-7e57a.firebasestorage.app',
    iosBundleId: 'com.example.eventPlaningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxEzuu_OPJ7aC8Jar-oAcjfar6rJWss_M',
    appId: '1:319261859233:web:33b7f2c704e07190cc3fe0',
    messagingSenderId: '319261859233',
    projectId: 'evently-app-7e57a',
    authDomain: 'evently-app-7e57a.firebaseapp.com',
    storageBucket: 'evently-app-7e57a.firebasestorage.app',
    measurementId: 'G-Y00ZTL4BST',
  );
}
